name: CI

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '18.15.0'
          registry-url: 'https://registry.yarnpkg.com'
      - run: yarn install --frozen-lockfile
      - run: yarn ci

